spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: authuser
    password: authpass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

