spring:
  application:
    name: auth-service

  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://postgres:5432/hoteldb
    username: hotelapp
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084

jwt:
  secret: ${JWT_SECRET:ZhV3+eY767wZQ4ce+qb8PbwanES3wA8XpBvAkC2ZiVA=}
  expiration: 86400000 # 24 saat

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG

